### PR TITLE
Making sure checkr is in good working order

### PR DESCRIPTION
**Pull request by dunkenwg**

### CODE REVIEW

**Comment by dunkenwg** [comment]
Actions are failing because the err package was archived. @joethorley, would you like me to remove all err functions or import an archived version of err?

**Comment by joethorley** [comment]
I had a look and the err package is not archived (was it recently unarchived)? Also the test for windows-latest (release) is passing so is something else going on? We are not quite ready to archive checkr.

**Comment by joethorley** [comment]
> > I had a look and the err package is not archived (was it recently unarchived)? Also the test for windows-latest (release) is passing so is something else going on? We are not quite ready to archive checkr.
> 
> Looks like err was removed from [CRAN](https://cran.r-project.org/web/packages/err/index.html). Would you like me to update the DESCRIPTION to load the GitHub version of err?
> 
> The ubuntu actions are failing because they are unable to find err. I'll look into why the mac os action is failing after we get the other actions working - I'm hoping it just starts working when we fix the err dependency.

Yes please update the DESCRIPTION file to use the github version of err (good sleuthing)

**Comment by dunkenwg** [comment]
Three tests are failing on ubuntu-latest (oldrel-1) with the same error:
```
Expected match: "y must be an atomic vector"
Actual message: "y must have 1 element"
```
The R-CMD-checks for the newer versions of R pass because the error message has changed to  `"y must be an atomic vector"`. Should we remove ubuntu-latest (oldrel-1), skip the tests that are failing on ubuntu-latest (oldrel-1), or make an internal function that will deal with these test failures?

**Comment by joethorley** [comment]
@dunkenwg - can you paste the test code that is causing the test failure on ubuntu-latest (oldrel-1)?

**Comment by dunkenwg** [comment]
They all have to do with calling `check_()` on `NULL`:
```
test_that("check_count errors", {
  y <- NULL
  expect_error(check_count(y), "y must be an atomic vector")
})
```
```
test_that("check_day errors", {
  y <- NULL
  expect_error(check_day(y), "y must be an atomic vector")
})
```
```
test_that("check_datetime errors", {
  y <- NULL
  expect_error(check_datetime(y), "y must be an atomic vector")
})
```

**Review by joethorley — APPROVED** [review]
I've added a commit that fixes the failing tests. Have a look and then we can discuss.

**Pull request merged**
